name: 'Publish'

# Only trigger, when the build workflow succeeded
# Triggers the workflow on push or pull request events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
        
      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@v1
        with:
          file-url: https://unpkg.com/altapay-js-api@1.0.2/package.json
          static-checking: localIsNew
          
      - name: Log when changed
#         if: steps.check.outputs.changed == 'true'
        run: 'echo "Version change found in commit ${{ steps.check.outputs.commit }}! New version: ${{ steps.check.outputs.version }} (${{ steps.check.outputs.type }})"'

      - name: Log when unchanged
#         if: steps.check.outputs.changed == 'false'
        run: 'echo "version change : ${{ steps.check.outputs.changed }}"'

      - name: Version update detected
        if: steps.check.outputs.changed == 'true'
        run: 'echo "Version change! -> ${{ steps.check.outputs.type }}"'

      - name: Install dependencies
        if: steps.check.outputs.changed == 'true'
        run: npm install

#       - name: Publish the package to NPM
#         if: steps.check.outputs.changed == 'true'
#         run: npm publish
#         env:
#           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # NPM will automatically authenticate with this
